FROM python:3.7-slim-buster

# install dependencies
RUN apt-get update
RUN apt-get install -y git-all python3-dev python3-pip python3-setuptools cmake build-essential libssl-dev
RUN apt-get install -y curl jq

WORKDIR /app

COPY ./requirements.txt ./

RUN pip install -r requirements.txt

COPY . .

RUN chmod +x /app/resources/catchup.sh

ENV API_PORT 3000

CMD ["gunicorn", "-b", "0.0.0.0:3000", "app"]